version: '3.9'

services:

  loader:
    container_name: loader
    build: ./back-end/loader
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8050:8050
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./back-end/loader:/usr/src/app

  db:
    container_name: mongodb
    build: ./back-end/mongodb
    env_file:
      - .env
    ports:
          - 27017:27017
    restart: always
    volumes:
      - mongodb_vol:/data/db      

volumes:
  mongodb_vol: